name: Yuanshen

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install mw2fcitx
        run: pip install mw2fcitx

      - name: Generate Dictionary File
        run: |
          MAX_RETRIES=10
          for i in $(seq 1 $MAX_RETRIES)
          do
            echo "Attempt $i/$MAX_RETRIES: Running dictionary generation..."
            mw2fcitx -c config_script.py || true

            if [ -f "yuanshen.dict.yaml" ]; then
              echo "Success: 'yuanshen.dict.yaml' was generated."
              exit 0
            fi

            if [ $i -lt $MAX_RETRIES ]; then
              echo "Warning: File not found after attempt $i. Retrying in 10 seconds..."
              sleep 10
            fi
          done
          
          echo "Error: Failed to generate dictionary file after $MAX_RETRIES attempts."
          exit 1

      - name: Set Dictionary Name
        run: |
          sed -i '2s/.*/name: yuanshen/' yuanshen.dict.yaml

      - name: Set Dictionary Version
        run: |
          DATE=$(TZ=Asia/Shanghai date +'%Y%m%d')
          sed -i "4s/.*/version: '$DATE'/" yuanshen.dict.yaml

      - name: Get Current Date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Update Latest Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "原神词库"
          body: |
            使用 mw2fcitx 自动生成的原神 Rime 拼音输入方案词库。
            最近更新于：${{ steps.date.outputs.date }}
          files: yuanshen.dict.yaml
